config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :pins

  root "pins#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
    before_action :find_pin, only: [:show, :edit, :update, :destroy]

    def index 
        @pins = Pin.all.order("created_at DESC")
    end 
    
    def show
    end

    def new
        @pin = current_user.pins.build
    end

    def create 
        @pin = current_user.pins.build(pin_params)

        if @pin.save
            redirect_to @pin, notice: "Successfully created new Pin"
        else
            render 'new'
        end
    end

    def edit 
    end

    def update
        if @pin.update(pin_params)
            redirect_to @pin, notice: "Successfully updated"
        else
            render 'edit'
        end
    end

    def destroy
        @pin.destroy
        redirect_to root_path
    end

    private 

    def pin_params
        params.require(:pin).permit(:title, :description)
    end

    def find_pin
        @pin = Pin.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pinboard
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-default
      .container
        .navbar-brand= link_to "Pin Board", root_path

        - if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "New Pin", new_pin_path
            %li= link_to "Account", edit_user_registration_path
            %li= link_to "Sign out", destroy_user_session_path, method: :delete
        - else 
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Sign up", new_user_registration_path
            %li= link_to "Sign in", new_user_session_path
    .container            
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert alert-info"
    
      = yield

app/views/pins/_form.html.haml
= simple_form_for(@pin, html: {multipart: true }) do |f|
  - if @pin.errors.any?
    #errors
    %h2
    = pluralize(@pin.errors.count, "error")
    prevented this Pin from saving
    %ul
    - @pin.errors.full_messages.each do |msg|
      %li= msg
  .form-group 
    = f.input :title, input_html: { class: 'form-control'}
    
  .form-group 
    = f.input :description, input_html: { class: 'form-control'}
    
  = f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
.col-md-6.col-md-offset-3
  %h1 Edit Form
  = render 'form'
  = link_to "Cancel", pin_path

app/views/pins/index.html.haml
- @pins.each do |pin|
    %h2= link_to pin.title, pin

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
  %h1 New Form
  = render 'form'
  = link_to "Back", root_path

app/views/pins/show.html.haml
%h1= @pin.title
%p= @pin.description
%p
Submitted by 
=@pin.user.email

%br/

= link_to "Back", root_path
= link_to "Edit", edit_pin_path
= link_to "Delete", pin_path, method: :delete, data: { confirm: 'You are sure?'}
